apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Match the labels of your backend pods
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
