replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

env:
  MYSQL_ROOT_PASSWORD: "" # Root password for MySQL (leave empty if no password)
  MYSQL_DATABASE: "inter" # Name of the database to be created
  MYSQL_USER: "root" # MySQL user
  MYSQL_PASSWORD: "" # MySQL user password (leave empty if no password)

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi # Size of the persistent volume claim

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Custom configuration
customConfig: |
  [mysqld]
  bind-address = 0.0.0.0
  sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
